### ISSUE TITLE
Indie Project Checkpoint 1 ready for review

### ISSUE THREAD

**Issue by kileader** [kileader/Budget-Game-Rankings#2]
@pawaitemadisoncollege checkpoint 1 work is complete
 
I feel that a majority of this work is figuring out how to work the APIs. I'm not sure how to put a timeline on that. I might do the professional development presentation on what I've learned from API tools I try.

I didn't realize when picking this that designing a database was so important. For tables, I think I would at least have users, a wishlist of games for each user, and settings for each user. I'm not exactly sure what role the Admin would play.

**Comment by pawaitemadisoncollege** [comment]
This sounds like a fun project @kileader and it looks like it will answer some interesting questions about games. I think you have done a nice job sizing the project and making sure it hits the project requirements. 

Nice job making regular entries and keeping up-to-date with your time log! 

- [ ] I think allowing the admin to do the kind fixing (editing/deleting) that you mentioned in the stories makes sense, and that story also enables you to hit the edit and delete project requirement (this is also covered in the wishlist). 
- [ ] You've done a nice job with a high level project plan - now it's time to work each user story into the plan. 
- [ ] Do you know which api/s you will be using to acquire the video game data?  Consuming restful apis is the topic for week 8, but there's no reason you can peek ahead at that if you want to get started on the api piece sooner than later! 
- [ ] Not really related to checkpoint 1, but something I noticed... I think this strange directory (screenshot below) is showing up because the filepath variable here is not defined in this file: https://github.com/kileader/Budget-Game-Rankings/blob/653735987b38f5c4b57df321e4d71daedd77a190/src/main/resources/log4j2.properties#L13. 
![Screen Shot 2021-02-15 at 2 00 41 PM](https://user-images.githubusercontent.com/13874466/107988807-69753a80-6f96-11eb-9e2c-b9bc036e37b1.png)

**Comment by kileader** [comment]
@pawaitemadisoncollege I've done some browsing for APIs, and I think I just need to try some out. The thing you noticed, I think I fixed it. I had a filename property defined, but I was trying to use filepath. I put up the Week 4 finished issue as well.
